# Generated by Django 5.1 on 2024-09-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='identificador',
        ),
        migrations.AddField(
            model_name='turma',
            name='unidade',
            field=models.CharField(default='Boa Viagem', max_length=100),
        ),
    ]
