# Generated by Django 5.1 on 2024-09-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_turma_identificador_turma_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='unidade',
            field=models.CharField(max_length=100),
        ),
    ]
