# Generated by Django 5.1 on 2024-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
