# Generated by Django 5.1 on 2024-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
