# Generated by Django 5.1 on 2024-10-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=12345678, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
