# Generated by Django 5.1 on 2024-10-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_aluno_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('turmas', models.ManyToManyField(related_name='simulados', to='cadastros.turma')),
            ],
        ),
    ]
