# Generated by Django 5.1 on 2024-10-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_turma_unidade_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cadastros.unidade'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
