# Generated by Django 5.1 on 2024-10-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_turma_unidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
