# Generated by Django 5.1 on 2024-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CM', 'Colégio Militar'), ('EA', 'Escola de Aplicação')], max_length=2)),
                ('data', models.DateField()),
            ],
        ),
    ]
