# Generated by Django 5.1 on 2024-10-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_simulado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos_mat', models.IntegerField(blank=True, null=True)),
                ('acertos_port', models.IntegerField(blank=True, null=True)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.simulado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
