# Generated by Django 5.0.4 on 2024-10-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_ver_geral',
            field=models.BooleanField(default=False, verbose_name='Permissão para Visualizar Ranking Geral'),
        ),
    ]
